[versions]
android-compile-sdk = "33"
android-gradle-plugin = "7.4.2"
android-min-sdk = "21"
android-target-sdk = "33"
androidx-activity = "1.5.0"
binary-compatibility-validator = "0.11.1"
dependency-guard = "0.4.3"
junit-jupiter = "5.8.2"
kotlin = "1.6.21"
kotlin-coroutines = "1.6.4"

[libraries]
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin" }
android-jar = 'com.google.android:android:4.1.1.4'
android-material = 'com.google.android.material:material:1.6.1'
androidx-activity = { module = "androidx.activity:activity", version.ref = "androidx-activity" }
androidx-appcompat = 'androidx.appcompat:appcompat:1.4.2'
androidx-constraintlayout = 'androidx.constraintlayout:constraintlayout:2.1.4'
androidx-core-ktx = 'androidx.core:core-ktx:1.8.0'
androidx-lifecycle-runtime-ktx = "androidx.lifecycle:lifecycle-runtime-ktx:2.5.1"
androidx-recyclerview = 'androidx.recyclerview:recyclerview:1.2.1'
apache-commons-lang = "org.apache.commons:commons-lang3:3.4"
appengine-api = 'com.google.appengine:appengine-api-1.0-sdk:1.9.38'
glide = 'com.github.bumptech.glide:glide:4.12.0'
guardsquare-proguard-gradle = 'com.guardsquare:proguard-gradle:7.3.1'
jackson-core = 'com.fasterxml.jackson.core:jackson-core:2.15.0'
jackson-databind = 'com.fasterxml.jackson.core:jackson-databind:2.15.0'
jetty-server = "org.eclipse.jetty:jetty-server:11.0.15"
json = "org.json:json:20230618"
jakarta-servlet-api = 'jakarta.servlet:jakarta.servlet-api:5.0.0'
jsr305 = 'com.google.code.findbugs:jsr305:3.0.2'
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-annotations-common = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version.ref = "kotlin" }
kotlin-test-common = { module = "org.jetbrains.kotlin:kotlin-test-common", version.ref = "kotlin" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
kotlin-test-jvm = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
okhttp2 = 'com.squareup.okhttp:okhttp:2.7.5'
okhttp3 = 'com.squareup.okhttp3:okhttp:4.0.0'

androidx-test-junit = 'androidx.test.ext:junit:1.1.3'
androidx-test-espresso-core = 'androidx.test.espresso:espresso-core:3.4.0'
appengine-api-labs = 'com.google.appengine:appengine-api-labs:1.9.38'
appengine-api-stubs = 'com.google.appengine:appengine-api-stubs:1.9.38'
appengine-testing = 'com.google.appengine:appengine-testing:1.9.38'
guava = 'com.google.guava:guava:19.0'
jmh-core = 'org.openjdk.jmh:jmh-core:1.12'
jmh-generator = 'org.openjdk.jmh:jmh-generator-annprocess:1.12'
mockito-core = 'org.mockito:mockito-core:5.4.0'
test-junit = 'junit:junit:4.13.2'
testng = 'org.testng:testng:6.9.10'
truth = "com.google.truth:truth:1.1.2"

[plugins]
binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binary-compatibility-validator" }
blind-pirate-osgi = "com.github.blindpirate.osgi:0.0.6"
dependency-guard = { id = "com.dropbox.dependency-guard", version.ref = "dependency-guard" }
gradle-version-plugin = "com.github.ben-manes.versions:0.42.0"
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
maven-publish-plugin = "com.vanniktech.maven.publish:0.24.0"